### ISSUE TITLE
Currents is not working with yarn 3

### ISSUE THREAD

**Issue by adrienharnay** [sorry-cypress/sorry-cypress#545] opened 2022-03-02 21:22 UTC
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Hello,

I just upgraded a project from Yarn 1 to Yarn 3 (without Plug'n'Play), and now Currents is not able to find cypress.

```
Error: Cannot detect cypress. Is cypress installed?
```

I see the code relies on `npm-which`, which has not been updated for 6 years. When logging into `getStateModulePath` in `cy2/lib/patch.js`, here is the result of the `candidates` variable:

```
[
  '/private/var/folders/kb/0ht5tzkd6knbz4wn7nfpnfwh0000gn/T/xfs-91d8a950/node_modules/cypress/lib/tasks/state.js',
  '/private/var/folders/kb/0ht5tzkd6knbz4wn7nfpnfwh0000gn/T/lib/tasks/state.js',
  '/private/var/folders/kb/0ht5tzkd6knbz4wn7nfpnfwh0000gn/T/cypress/lib/tasks/state.js'
]
```

Do you think the logic could be updated to support Yarn 3 as more and more people are migrating to it?

Thanks in advance and have a nice evening

## How to reproduce

1. Install Yarn 3 in a repository
2. Install cypress
3. Try to run currents

## Relevant logs / screenshots

Included above

## Environment

- sorry-cypress version: "@currents/cli": "1.0.8",
- cypress version: "cypress": "9.5.0",
- platform: docker
- service: api

**Comment by agoldis** [comment] 2022-03-02 21:26
@adrienharnay thanks for reporting that, on it!

**Comment by agoldis** [comment] 2022-03-02 21:34
Duplicate of https://github.com/currents-dev/cli/issues/3

**Closed by agoldis** 2022-03-02 21:34 UTC

**Comment by adrienharnay** [comment] 2022-03-02 22:11
Thank you! Sorry I was not sure where to post the issue since this repository seemed to have more traction than the other one.

Please let me know if I can do anything to help!
