### ISSUE TITLE
Create a helm chart

### ISSUE THREAD

**Issue by fsmaia** [sorry-cypress/sorry-cypress#240] opened 2020-12-23 04:38 UTC
- [x] I have seached issues for similar feature requests

## What is this feature about (1 sentence)

This feature is about having a helm chart to automate deployment using [Helm](https://github.com/helm/helm)

## Why is it needed? What is the value? For whom do we build it?

In one of the main guides listed in the docs, the writer used a tool to create a Helm chart:
https://medium.com/@adityahbk/cypress-parallelization-on-jenkins-using-sorry-cypress-197a86ad8ed1

IMHO it would increase the popularity of this amazing tool, and it would make it easier to deploy, also by forcing some sane defaults.

## High-level feature overview

Taking lighthouse-ci and sonarqube as examples:
* https://github.com/sebastien-prudhomme/cowboysysop-charts/tree/lighthouse-ci/charts/lighthouse-ci
* https://github.com/Oteemo/charts/tree/master/charts/sonarqube

They added a boilerplate to make the repo a Helm chart repository. I haven't seen any Helm charts within a regular repository like this one, so I don't know if a packages/helm directory would be enough, or if additional boilerplate would be required.

**Comment by tico24** [comment] 2020-12-23 05:52
I'll take this. It'll probably be in its own repo (at least initially) due to how the Helm releases work.

**Comment by tico24** [comment] 2020-12-23 08:51
I've had a first stab at it. It's currently in my own repo [here](https://github.com/tico24/sorry-cypress-helm/tree/main/sorry-cypress-helm) because I'm nowhere near ready to taint this repo with it!

It's very opinionated, but seems to work with the minimal testing I've done. Would appreciate your feedback.

**Comment by tico24** [comment] 2020-12-23 13:00
I've now spent a few hours on it and its reasonably robust. I believe it's probably "good enough" for an initial release, and then we can grow/tweak it as requirements come through. I'd still appreciate some real-world usage so let me know your thoughts @agoldis @fsmaia.

The default deployment is a non-persistent affair. This should make it easier for new people to deploy. However, persistent mongo and S3 access is available and configurable in the values.yml with examples. I believe I've included options for all the various environment variables that are documented.

@agoldis There's a couple of things I can think of that'll need some thought before we merge in:

**1. Where should it live?**
The helm chart should get released whenever the software gets a release update, but it'll also probably get released in between those periods (bug fixes, enhancements etc). I don't know your release flow, but maybe if this interferes with your releases, it should have it's own repo?

2. Rather than having someone download the code and build their own helm chart, **we should host a helm repo somewhere.** I'm not super familiar with github, but according to google it can be a helm chart repo with some config (that you'll probably have to do I'm afraid).

2a. If we're feeling fancy and want a wider audience, we should put it on [Artifact Hub](https://artifacthub.io/) (formerly Helm Hub). It's like a search engine for helm charts... akin to Docker Hub (although it doesn't actually hold the charts themselves).

Once 1 and 2 are agreed, I don't mind knocking together some basic documentation to go on the website too. That said, I'll be winding down for Christmas soon so there might be a small delay. Not necessarily a bad thing.. a few people can try it, we can tweak based on initial feedback and then make it more obvious that it exists.

**Comment by fsmaia** [comment] 2020-12-23 14:30
Wow, can't thank you enough! It looks amazing!

We could configure [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action), it seems simple and takes a few steps to be ready to go.

Bringing in some examples and the relevant config files:

1. https://github.com/cowboysysop/charts
   - [.github/workflows/release.yml](https://github.com/cowboysysop/charts/blob/master/.github/workflows/release.yml)
   - [.github/workflows/lint-test.yaml](https://github.com/cowboysysop/charts/blob/master/.github/workflows/lint-test.yaml) (Bonus)
   - [ct.yaml](https://github.com/cowboysysop/charts/blob/master/ct.yaml) (Related to lint-test)

2. https://github.com/Oteemo/charts
   - [.github/workflows/release.yml](https://github.com/Oteemo/charts/blob/master/.github/workflows/release.yml)
   - [.github/workflows/lint-test.yaml](https://github.com/Oteemo/charts/blob/master/.github/workflows/lint-test.yml)
   - [test.yaml](https://github.com/Oteemo/charts/blob/master/test.yaml)
   - [lint.yaml](https://github.com/Oteemo/charts/blob/master/lint.yaml)

Even without deciding the release workflow or the final repository, I believe we could already add this boilerplate.

What do you think?

Just reminding that I'm fully available to help!

**Comment by tico24** [comment] 2020-12-23 20:05
Sounds like a plan. Feel feee to do a PR to my repo if you want to try that... or maybe I'll get a decision on where this code should go and I'll pull my stuff in and you can merge there.

**Comment by fsmaia** [comment] 2020-12-24 00:19
Just opened the pull-requests:
* https://github.com/tico24/sorry-cypress-helm/pull/1 (helm/chart-releaser-action)
* https://github.com/tico24/sorry-cypress-helm/pull/2 (gh-pages)

IMHO the final repository could live in https://github.com/sorry-cypress/charts, so the repository would be hosted in https://sorry-cypress.github.io/charts.

**Comment by agoldis** [comment] 2020-12-24 06:23
@tico24 @fsmaia Wow, that's awesome! I am a complete newbie to this quantum technology (help charts), just started reading and grasping the wisdom of greater minds.

At glance:
 - I imagine it would be easier to run a "full" working example with `minio` screenshots support - it allows running the whole bundle w/o any external dependencies. May be it's worth to have some kind of minio in "charts"?



> 1. Where should it live?

Ideally at https://github.com/sorry-cypress/charts, as @fsmaia suggested. I have added you both to the team, I think you can create as a member, but I have created one: https://github.com/sorry-cypress/charts. If you want a different name, I really don't have  a strong opinion.

> get released whenever the software gets a release update...  probably get released in between those periods (bug fixes, enhancements etc)

`sorry-cypress` gets released with every new push to `master` (that releases `latest` tags to dockerhub`) and / or semantic-version tag push, e.g. `v1.0.3` - it updates /creates tags `v1`, `v1.0` etc. It's all done via [GitHub Actions](https://github.com/sorry-cypress/sorry-cypress/blob/master/.github/workflows/dockerimage.yml).

I am thinking of:
 - each change to `charts` repo itself can trigger release actions as [proposed](https://github.com/sorry-cypress/sorry-cypress/issues/240#issuecomment-750324744)
- when there's a new version of sorry-cypress, we can use [repository dispatch](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch) event to trigger `chart` release actions


> If we're feeling fancy and want a wider audience, we should put it on Artifact Hub (formerly Helm Hub).

I am feeling fancy :) if that helps people to discover and use it

**Comment by tico24** [comment] 2020-12-24 06:56
I'm on mobile so please forgive brevity... I wanted to catch you before the end of your day. 

Minio would be a dependency because the right way to do it would be to pull in their helm chart. It can be done, but I wanted you to be aware.  I have a couple of hours today so I will look to include that. 

The same goes for mongo, although I've not yet managed to get sorry-cypress working with the mongo helm. 

In order to release a new version of the helm chart, you have to increase the version number in chart.yml. Just building on a change in that directory won't work. This can of course be automated, but probably shouldn't just so that a change log can be kept.

**Comment by agoldis** [comment] 2020-12-24 07:04
@tico24 no problem at all! 

If there's something that seems unnecessary / too complex, let's skip it for now and release something simple that works. We can iterate later and handle release / external charts... may be more people will contribute and make it better.

As a simple alternative I can just release manually or write a simple script...

**Comment by tico24** [comment] 2020-12-24 07:36
I tried to pop a PR in, but have spectacularly failed! https://github.com/sorry-cypress/sorry-cypress/pull/242

**Comment by tico24** [comment] 2020-12-24 08:12
I think some of the issue is that I can't create a "gh-pages" branch on your repo @agoldis. Once that's done, I can do a PR for that piece of the puzzle. I'm not great at github, sorry!

**Comment by fsmaia** [comment] 2020-12-26 18:04
I also liked having this repository as the helm repository with a charts folder on it. As our docs are in another repository, we won't miss the GH pages in this one. But IMHO it is a personal preference after all. My favorite choice is still having a dedicated charts repository :smile: 

In addition to #242, I tried to open a PR adding the `gh-pages` branch, but as @tico24 said, you need to create it first.

However, if we decide that the final repo will be sorry-cypress/charts, either you can create the `gh-pages` branch or set us as maintainers, so we can configure it.

**Comment by fsmaia** [comment] 2021-01-05 23:46
Up :)

**Comment by tim-sendible** [comment] 2021-01-06 06:07
> I also think we could use tico24's repository to perform the first tests, so we can land in the final repository with an initially stable version (instead of doing test commits/pull-requests).

Please don't use my repo for the first tests. 2 reasons:
1. I have merged it into my fork of sorry-cypress already so it's out of date
2. It broke my website because I am using gh-pages for my blog :)

**Comment by tim-sendible** [comment] 2021-01-06 06:08
That said, the tests in my fork of this repo do pass, so I think simply creating the gh-pages branch and allowing us to do thos 2 PRs should be enough.

**Comment by tico24** [comment] 2021-01-06 06:08
> I also think we could use tico24's repository to perform the first tests, so we can land in the final repository with an initially stable version (instead of doing test commits/pull-requests).

Please don't use my repo for the first tests. 2 reasons:
1. I have merged it into my fork of sorry-cypress already so it's out of date
2. It broke my website because I am using gh-pages for my blog :)

**Comment by agoldis** [comment] 2021-01-06 06:16
@tico24 @fsmaia I was sure that adding org members would grant sufficient permissions to create branches etc... apparently not. I have invited you to a team that has maintainer access to this repo, and admin for https://github.com/sorry-cypress/charts

Please tell me if that's sufficient

**Comment by tico24** [comment] 2021-01-06 11:16
ok - after a fair bit of trial and error, here's where we are at:

1. The sorry-cypress repo no longer has helm things in it.
2. The charts repo does.
3. Lint on PR now works

**Comment by fsmaia** [comment] 2021-01-06 12:23
Amazing guys! I'm really sorry for not helping/interacting before, it was due to the Brazil timezone.

About the K8s version, count on me @tico24.

Yep, I agree with closing this issue and using the sorry-cypress/charts for further discussions o/

**Comment by tico24** [comment] 2021-01-06 12:31
Nothing to apologise for. I think we're in 3 different countries, although I can never work out @agoldis because he seems to be up when I think he should be asleep!

**Comment by tico24** [comment] 2021-01-06 18:48
One more thing @agoldis. I would suggest we now remove the Kubernetes yaml examples that I added before. 

If people are running kubernetes they can easily run helm and the helm chart is much more flexible than the original yaml.

**Comment by agoldis** [comment] 2021-01-06 19:02
@tico24 sure, that makes sense! https://sorry-cypress.dev/installation/kubernetes is the only documentation we have, I can just point to your blog post.

**Comment by tico24** [comment] 2021-01-06 19:03
My blog post is up. It's admittedly very sparse though!

**Comment by tico24** [comment] 2021-01-11 07:42
I think we can probably close this.

**Closed by tico24** 2021-01-11 07:42 UTC
Labels: integration
